create table if not exists memos
(
    id                       uuid      default gen_random_uuid() not null
        primary key,
    memo_number_prefix       varchar(50)                         not null,
    memo_number_sequence     integer generated by default as identity,
    department_code          varchar(50)                         not null,
    title                    varchar(500)                        not null,
    purpose                  text,
    created_at               timestamptz default now()           not null,
    updated_at               timestamptz
);

alter table memos
    owner to root;

grant delete, insert, select, update on memos to fkrahmad_be;

create table if not exists email_outbox
(
    id                uuid primary key default gen_random_uuid(),
    memo_id           uuid references memos (id)           not null,
    event_type        varchar(100)                         not null,
    payload           jsonb                                not null,
    recipient_email   varchar(255)                         not null,
    notification_type varchar(100)                         not null,
    status            varchar(20)  default 'PENDING'       not null,
    retry_count       integer       default 0              not null,
    last_attempt_at   timestamptz,
    sent_at           timestamptz,
    error_message     text,
    idempotency_key   varchar(100),
    meta_created_at   timestamptz   default now()          not null,
    meta_updated_at   timestamptz
);
create unique index if not exists ux_email_outbox_idempotent
    on email_outbox (idempotency_key);

create index if not exists ix_email_outbox_status_created_at
    on email_outbox (status, meta_created_at);

create index if not exists ix_email_outbox_memo_id
    on email_outbox (memo_id);

alter table email_outbox
    owner to root;

grant delete, insert, select, update on email_outbox to fkrahmad_be;

