// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/fikriahmadf/outbox-examples/external/domain/notif_publisher/service"
	"github.com/fikriahmadf/outbox-examples/infras"
	"github.com/fikriahmadf/outbox-examples/internal/domain/internal_memo/repository"
	"github.com/fikriahmadf/outbox-examples/internal/handlers/internal_memo"
	"github.com/fikriahmadf/outbox-examples/transport/http"
	"github.com/fikriahmadf/outbox-examples/transport/http/router"
)

// Injectors from wire.go:

// InitializeServer constructs the HTTP server with all handlers using compile-time DI.
func InitializeServer() (*http.HTTP, error) {
	config := ProvideConfig()
	postgresConn := infras.ProvidePostgresConn(config)
	internalMemoRepositoryPostgres := repository.ProvideInternalMemoRepositoryPostgres(postgresConn)
	externalNotifPublisherServiceImpl := service.ProvideNotifPublisherService(config)
	memoHandler := internal_memo.ProvideMemoHandler(config, internalMemoRepositoryPostgres, externalNotifPublisherServiceImpl)
	domainHandlers := router.ProvideDomainHandlers(memoHandler)
	routerRouter := router.ProvideRouter(domainHandlers)
	httpHTTP := http.ProvideHTTP(postgresConn, config, routerRouter)
	return httpHTTP, nil
}
